sudo killall a2jmidid
sudo killall /opt/bitwig-studio/bin/BitwigStudio
sudo killall pd
sudo killall bitwig
sudo killall krita
sudo killall /usr/lib/open-stage-control/open-stage-control
sudo killall /home/psc/11h11/thereminacrayon/xinputOSC/xinputOSC
sudo killall ttymidi
sudo killall /home/psc/11h11/thereminacrayon/ttymidi/ttymidi
sudo killall /usr/bin/python
sudo killall touchegg
sudo killall carla
sudo killall simplescreenrecorder
